export const DESCRICAO_LEVANTAMENTO_RADIOPROTECAO = [
  {
    descricao: 'LEVANTAMENTO RADIOMÉTRICO DE AREA',
    valor: 'LEVANTAMENTO RADIOMETRICO DE AREA'
  },
  {
    descricao: 'LEVANTAMENTO RADIOMÉTRICO CABINE DOSE INTEGRADA',
    valor: 'LEVANTAMENTO RADIOMETRICO CABINE DOSE INTEGRADA'
  },
  {
    descricao: 'LEVANTAMENTO RADIOMÉTRICO CABINE TAXA EXPOSICAO',
    valor: 'LEVANTAMENTO RADIOMETRICO CABINE TAXA EXPOSICAO'
  },
  {
    descricao: 'LEVANTAMENTO RADIOMÉTRICO DA UNIDADE GERADORA DE RAIOS X - 7B',
    valor: 'LEVANTAMENTO RADIOMETRICO DA UNIDADE GERADORA DE RAIOS X - 7B'
  },
  {
    descricao:
      'LEVANTAMENTO RADIOMÉTRICO APOS ALERTA VERMELHO DO SISTEMA DE DETECÇÃO DE RADIAÇÃO NA CARGA',
    valor:
      'LEVANTAMENTO RADIOMETRICO APOS ALERTA VERMELHO DO SISTEMA DE DETECCAO DE RADIACAO NA CARGA'
  },
  {
    descricao: 'LISTA DE VERIFICAÇÃO DE PROCESSO',
    valor: 'LISTA DE VERIFICAÇÃO DE PROCESSO'
  }
];
